### ISSUE TITLE
create template for bug report

### ISSUE THREAD

**Issue by lkoczwara** [Mai-ah/test#1]

**Comment by lkoczwara** [comment]
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

**Comment by Mai-ah** [comment]
Done. Zanim zamknę potwiedź mi proszę (lub wręcz przeciwnie) czy o to chodziło. Znaczników w Markdown jest oczywiście więcej, mogę je "na siłę" użyć. Ale w takiej formie jak jest teraz jest moim zdaniem prosto i przerzyście.

**Comment by lkoczwara** [comment]
jest super, zamykam to `issue` :)
